pipeline {
    agent any
    stages {
        stage('Dev') {
            steps {
                echo 'Building..'
		checkout scm
		sh './mvn_package.sh'
		sh './webfront_build.sh'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
