pipeline {
    agent any

    node {
        stage('Dev') {
            steps {
                echo 'Building..'
		checkout scm
		sh mvn_packaage
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
