pipeline {
    agent any
    stages {
        stage('Dev') {
            steps {
                echo 'Building..'
		checkout scm
		sh 'mvn_package'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
