version: '3.3'

services:
  icin_cicd:
    image: brianharmon1970/icin_cicd:0.0.1
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 8083:8080
      - 50000:50000
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - cicd_network.net
    # Where our data will be persisted
    volumes:
      - type: volume
        source: icin-cicd.db
        target: /var/lib/jenkins
    
networks:
    cicd_network.net:

# Names our volume
volumes:
    icin-cicd.db:

